--------------------------------------------------------
--  Constraints for Table LK_EMAILS_GUIDS
--------------------------------------------------------

  ALTER TABLE "FCR"."LK_EMAILS_GUIDS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_EMAILS_GUIDS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_EMAILS_GUIDS" ADD CONSTRAINT "LK_EMAILS_GUIDS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_11801091090798670"  ENABLE;
  ALTER TABLE "FCR"."LK_EMAILS_GUIDS" MODIFY ("ROW_TIME" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_EMAILS_GUIDS" MODIFY ("GUID" NOT NULL ENABLE);
