--------------------------------------------------------
--  DDL for Index LK_USER_ACCOUNTS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FCR"."LK_USER_ACCOUNTS_UK1" ON "FCR"."LK_USER_ACCOUNTS" ("USER_ID", "ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_11801091090798670" ;
