--------------------------------------------------------
--  Constraints for Table LK_USER_ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" ADD CONSTRAINT "LK_MYROOMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_11801091090798670"  ENABLE;
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" MODIFY ("HOUSE_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" MODIFY ("ACCOUNT_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" ADD CONSTRAINT "LK_USER_ACCOUNTS_UK1" UNIQUE ("USER_ID", "ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APEX_11801091090798670"  ENABLE;
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" MODIFY ("ROOM_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" MODIFY ("FLAT_NUM" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "FCR"."LK_USER_ACCOUNTS" MODIFY ("ROW_TIME" NOT NULL ENABLE);
