--------------------------------------------------------
--  DDL for View V_TOTAL_ACCOUNT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FCR"."V_TOTAL_ACCOUNT" ("HOUSE_ID", "ROOMS_ID", "FLAT_NUM", "ACCOUNT_ID", "END_ACCOUNT_MN", "MN", "PERIOD", "CHARGE_SUM_MN", "CHARGE_SUM_TOTAL", "PAY_SUM_MN", "PAY_SUM_TOTAL", "PENI_SUM_MN", "PENI_SUM_TOTAL", "BARTER_SUM_MN", "BARTER_SUM_TOTAL", "DOLG_SUM_MN", "DOLG_SUM_TOTAL", "ROW_TIME") AS 
  select "HOUSE_ID","ROOMS_ID","FLAT_NUM","ACCOUNT_ID","END_ACCOUNT_MN","MN","PERIOD","CHARGE_SUM_MN","CHARGE_SUM_TOTAL","PAY_SUM_MN","PAY_SUM_TOTAL","PENI_SUM_MN","PENI_SUM_TOTAL","BARTER_SUM_MN","BARTER_SUM_TOTAL","DOLG_SUM_MN","DOLG_SUM_TOTAL","ROW_TIME" from fcr.t#total_account@dbl_fcr1
;
